### ISSUE TITLE
Incorrect icon and how do you change color?

### ISSUE THREAD

**Issue by doughsay** [miguel-s/ex_fontawesome#4]
Hey, sorry for filing a combined issue, but I just stumbled on this package and it looks cool.  But,I can't figure out how to set the color of the icons...  I'm using tailwind and I'm trying to use the text-color helpers, but they have no effect. 

How are you meant to control the icon color?

Secondly: the first icon I tried using is `headphones` solid: https://fontawesome.com/icons/headphones?s=solid
And it looks nothing like this icon.  It produces a completely different SVG from what is copied from the official fontawesome website.  See screenshot:
![DeepinScreenshot_select-area_20220220194258](https://user-images.githubusercontent.com/221693/154885594-14796757-6500-426c-8d91-6f655e25354d.png)

Why is the icon wrong?

**Comment by miguel-s** [comment]
Hi @doughsay!

#### Setting the color of the icons

All classes you set in the `class` prop are passed down to the svg tag, so you can style these icons like any regular svg.

If you're using Tailwind CSS 3 you can use the `stroke-color` and `fill-color` utilities:
`<FontAwesome type="solid" name="headphones" class="h-4 w-4 stroke-red-500" />`

If you're using Tailwind CSS 2 you can use the `text-color` utility, but you also have to set "fill-current":
`<FontAwesome type="solid" name="headphones" class="h-4 w-4 text-red-500 fill-current" />`

#### Headphone icon

You're seeing a different headphones icon because this package is still using FontAwesome 5. Here's the link to that version of the headphones icon https://fontawesome.com/v5/icons/headphones?s=solid

I'll upgrade to FontAwesome 6 later today.

**Comment by doughsay** [comment]
Oh, oops, I saw that your package version was 0.6.0 and thought that meant it was using FontAwesome 6 already, silly assumption 😅.  I also didn't realize version 6 was so new!

Thanks for pointing me to those other color utility classes, I was unaware of them.

Thanks for the response and I'm looking forward to the update!

**Comment by miguel-s** [comment]
Just released version 0.7.0 with FontAwesome 6 😃
