### ISSUE TITLE
Possible to get the <i> elements?

### ISSUE THREAD

**Issue by danielniccoli** [miguel-s/ex_fontawesome#6]
Is it possible to get the `<i>` elements in the rendered code, such as `<i class="fa-solid fa-bars-staggered fa-fw"></i>`?

**Comment by miguel-s** [comment]
Hi @danielniccoli!

Thanks for the suggestion :)

For simplicity I'm limiting the scope of this library to SVGs only.
The reason is that getting the SVGs into your project is quite messy and difficult without help of a library.
However, the FontAwesome package already makes using the `<i>` elements directly much simpler than using their SVGs.

Hope this clarifies!

**Comment by danielniccoli** [comment]
Thanks for the answer.
